/**
 * AI Dispute Types and Zod Schemas
 *
 * These types define the data structures used by the AI evidence planning
 * and argument generation systems.
 */

import { z } from "zod";

// =============================================================================
// Evidence Category Types
// =============================================================================

/**
 * Evidence categories map to the different systems/sources at a hotel
 * that can provide evidence for dispute responses.
 */
export const EvidenceCategorySchema = z.enum([
  "pms_data", // Property Management System data (folios, registration cards)
  "policy", // Cancellation, refund, terms policies
  "proof_of_stay", // Check-in/out records, keycard logs, housekeeping
  "communications", // Email, chat, phone logs, confirmations
  "payment_data", // Authorization, settlement, AVS/CVV data
  "incident_reports", // Damage reports, complaints, incident logs
  "delivery", // Shipping/tracking (rarely used in hotels)
  "other", // Miscellaneous evidence
]);

export type EvidenceCategory = z.infer<typeof EvidenceCategorySchema>;

// =============================================================================
// Evidence Requirement Types
// =============================================================================

/**
 * Status of an individual evidence requirement
 */
export const EvidenceRequirementStatusSchema = z.enum([
  "pending", // Not yet uploaded
  "uploaded", // File has been uploaded
  "not_available", // Marked as not available by user
  "not_applicable", // Doesn't apply to this dispute
]);

export type EvidenceRequirementStatus = z.infer<
  typeof EvidenceRequirementStatusSchema
>;

/**
 * Individual evidence requirement generated by the AI
 */
export const EvidenceRequirementSchema = z.object({
  id: z.string(),
  category: EvidenceCategorySchema,
  label: z.string(),
  tag: z.string().optional(), // Structured identifier for dedup (e.g., "folio", "cancellation_policy", "registration_card")
  description: z.string(),
  example: z.string().optional(),
  sourceHint: z.string().optional(), // Where to get this (e.g., "Front Desk", "Finance")
  instructions: z.string().optional(), // Specific actionable steps to gather this evidence
  required: z.boolean(),
  priority: z.number(), // 1 = highest priority
});

export type EvidenceRequirement = z.infer<typeof EvidenceRequirementSchema>;

// =============================================================================
// Evidence Item (Tracking) Types
// =============================================================================

/**
 * Evidence item - tracks the status of a requirement and any uploaded files
 */
export const EvidenceItemSchema = z.object({
  requirementId: z.string(),
  status: EvidenceRequirementStatusSchema,
  fileId: z.string().optional(), // Firebase Storage file ID
  fileName: z.string().optional(),
  uploadedAt: z.string().optional(), // ISO date string
  uploadedBy: z.string().optional(), // User ID
  notes: z.string().optional(),
});

export type EvidenceItem = z.infer<typeof EvidenceItemSchema>;

// =============================================================================
// Dispute Classification Types
// =============================================================================

/**
 * Card network that issued the dispute
 */
export const CardNetworkSchema = z.enum([
  "visa",
  "mastercard",
  "amex",
  "discover",
  "unknown",
]);

export type CardNetwork = z.infer<typeof CardNetworkSchema>;

// =============================================================================
// Evidence Plan Types
// =============================================================================

/**
 * The complete evidence plan generated by the AI for a dispute
 */
export const EvidencePlanSchema = z.object({
  // Classification
  disputeCategory: z.string(),
  disputeSubtype: z.string().optional(),
  reasonCode: z.string().optional(),
  network: CardNetworkSchema.optional(),
  
  // Recommendation
  recommendation: z.enum(["fight", "accept"]),
  winnability: z.enum(["high", "medium", "low"]),
  winnabilityReason: z.string(),
  
  // Evidence requirements
  requirements: z.array(EvidenceRequirementSchema),

  // Summary
  summary: z.string(),
  
  // Metadata
  generatedAt: z.string().optional(),
  model: z.string().optional(),
});

export type EvidencePlan = z.infer<typeof EvidencePlanSchema>;

// =============================================================================
// Dispute Case Types (Input to AI)
// =============================================================================

/**
 * Booking information from PMS
 */
export const BookingInfoSchema = z.object({
  checkIn: z.string().optional(), // ISO date string
  checkOut: z.string().optional(),
  roomNumber: z.string().optional(),
  roomType: z.string().optional(),
  ratePlan: z.string().optional(),
  totalAmount: z.number().optional(),
  currency: z.string().optional(),
  status: z.string().optional(), // booked, checked-in, checked-out, cancelled, no-show
  guestName: z.string().optional(),
});

export type BookingInfo = z.infer<typeof BookingInfoSchema>;

/**
 * Guest information from PMS
 */
export const GuestInfoSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
});

export type GuestInfo = z.infer<typeof GuestInfoSchema>;

/**
 * Hotel profile and policies
 */
export const HotelProfileSchema = z.object({
  name: z.string(),
  location: z.string().optional(),
  policies: z
    .object({
      cancellation: z.string().optional(),
      refund: z.string().optional(),
      noShow: z.string().optional(),
    })
    .optional(),
});

export type HotelProfile = z.infer<typeof HotelProfileSchema>;

/**
 * Payment gateway data
 */
export const PaymentDataSchema = z.object({
  last4: z.string().optional(),
  authCode: z.string().optional(),
  avsMatch: z.boolean().optional(),
  cvvMatch: z.boolean().optional(),
  threeDSecure: z.boolean().optional(),
});

export type PaymentData = z.infer<typeof PaymentDataSchema>;

/**
 * Complete dispute case - all data the AI needs to generate a plan
 */
export const DisputeCaseSchema = z.object({
  // Core dispute info
  disputeId: z.string(),
  organizationId: z.string(),
  pspProvider: z.enum(["stripe", "adyen"]),
  pspDisputeId: z.string().optional(),
  pspReasonCode: z.string().optional(),

  // Dispute details
  amount: z.number(),
  currency: z.string(),
  reason: z.string().nullable(),
  customerExplanation: z.string().optional(),
  transactionDate: z.string().optional(), // ISO date string
  respondByDate: z.string().optional(),

  // Linked data
  hotelProfile: HotelProfileSchema.optional(),
  booking: BookingInfoSchema.nullable().optional(),
  guest: GuestInfoSchema.nullable().optional(),
  paymentData: PaymentDataSchema.optional(),

  // Industry vertical (drives prompt selection in evidence planning pipeline)
  merchantVertical: z.enum(["hospitality", "ticketing", "general"]).optional(),
});

export type DisputeCase = z.infer<typeof DisputeCaseSchema>;

// =============================================================================
// Dispute Argument Types (Output from Argument Generator)
// =============================================================================

/**
 * A paragraph in the dispute argument
 */
export const ArgumentParagraphSchema = z.object({
  heading: z.string(),
  content: z.string(),
  evidenceReferences: z.array(z.string()).optional(), // IDs of evidence items
});

export type ArgumentParagraph = z.infer<typeof ArgumentParagraphSchema>;

/**
 * Timeline event for the argument
 */
export const TimelineEventSchema = z.object({
  date: z.string(), // ISO date string
  description: z.string(),
  evidenceId: z.string().optional(),
});

export type TimelineEvent = z.infer<typeof TimelineEventSchema>;

/**
 * Complete dispute argument generated by AI
 */
export const DisputeArgumentSchema = z.object({
  // Summary
  executiveSummary: z.string(),
  
  // Timeline
  timeline: z.array(TimelineEventSchema),
  
  // Main argument
  paragraphs: z.array(ArgumentParagraphSchema),

  // Key claims and rebuttals
  customerClaimRebuttal: z.string().optional(),
  
  // Conclusion
  conclusion: z.string(),
  
  // PSP-specific fields (for Stripe/Adyen submission)
  uncategorizedText: z.string().optional(),
  productDescription: z.string().optional(),
  customerName: z.string().optional(),
  customerEmail: z.string().optional(),
  billingAddress: z.string().optional(),
  shippingAddress: z.string().optional(),
  customerSignature: z.string().optional(),
  receipt: z.string().optional(),
  serviceDates: z.string().optional(),
  cancellationPolicy: z.string().optional(),
  cancellationPolicyDisclosure: z.string().optional(),
  refundPolicy: z.string().optional(),
  refundPolicyDisclosure: z.string().optional(),
  refundRefusalExplanation: z.string().optional(),
  customerCommunication: z.string().optional(),
  
  // Metadata
  generatedAt: z.string().optional(),
  model: z.string().optional(),
  version: z.number().optional(),
});

export type DisputeArgument = z.infer<typeof DisputeArgumentSchema>;

// =============================================================================
// Version History Types
// =============================================================================

/**
 * Version history entry for evidence plans
 */
export interface EvidencePlanVersion {
  plan: EvidencePlan;
  evidenceItems: EvidenceItem[];
  generatedAt: Date;
  version: number;
  isCurrent: boolean;
}

/**
 * Version history entry for argument drafts
 */
export interface ArgumentVersion {
  argument: DisputeArgument;
  generatedAt: Date;
  version: number;
  isCurrent: boolean;
  isSubmitted: boolean;
  submittedAt?: Date;
}

// =============================================================================
// Specialist Types - Claim Analyst
// =============================================================================

/**
 * Type of claim the customer is making
 */
export const ClaimTypeSchema = z.enum([
  "fraud",           // Customer claims they didn't authorize the transaction
  "cancellation",    // Customer claims they cancelled or policy wasn't disclosed
  "service",         // Customer claims service wasn't provided or was inadequate
  "authorization",   // Customer claims transaction wasn't properly authorized
  "other",           // Other dispute types
]);

export type ClaimType = z.infer<typeof ClaimTypeSchema>;

/**
 * Output from the Claim Analyst specialist
 * Analyzes the customer's claim to identify what needs to be disproven
 */
export const ClaimAnalysisSchema = z.object({
  claimType: ClaimTypeSchema,
  customerArguments: z.array(z.string()),      // What they're claiming
  weakPoints: z.array(z.string()),             // Where their claim can be attacked
  requiredDisproofs: z.array(z.string()),      // What evidence would disprove each argument
  suggestedCounterarguments: z.array(z.string()),
});

export type ClaimAnalysis = z.infer<typeof ClaimAnalysisSchema>;

// =============================================================================
// Specialist Types - Evidence Analyzer
// =============================================================================

/**
 * Policy type extracted from organization documents
 */
export const PolicyTypeSchema = z.enum([
  "cancellation",
  "refund",
  "terms",
  "other",
]);

export type PolicyType = z.infer<typeof PolicyTypeSchema>;

/**
 * Available document in the organization
 */
export const AvailableDocumentSchema = z.object({
  id: z.string(),
  name: z.string(),
  category: z.string(),
  relevantForDispute: z.boolean(),
});

export type AvailableDocument = z.infer<typeof AvailableDocumentSchema>;

/**
 * Extracted policy from organization documents
 */
export const ExtractedPolicySchema = z.object({
  type: PolicyTypeSchema,
  documentId: z.string(),
  summary: z.string(),
});

export type ExtractedPolicy = z.infer<typeof ExtractedPolicySchema>;

/**
 * Argument coverage analysis - how well existing documents cover customer claims
 */
export const ArgumentCoverageSchema = z.object({
  customerArgument: z.string(),
  coveredBy: z.array(z.string()).optional(), // Document IDs/names that address this argument
  gapDescription: z.string().optional(),
  gapSeverity: z.enum(["critical", "moderate", "minor"]),
});

export type ArgumentCoverage = z.infer<typeof ArgumentCoverageSchema>;

/**
 * Output from the Evidence Analyzer specialist
 * Extracts information from the hotel's existing organization documents
 */
export const ExistingEvidenceAnalysisSchema = z.object({
  availableDocuments: z.array(AvailableDocumentSchema),
  extractedPolicies: z.array(ExtractedPolicySchema),
  missingDocuments: z.array(z.string()),  // What the hotel should have but doesn't
  argumentCoverage: z.array(ArgumentCoverageSchema).optional(), // How well docs cover customer claims
});

export type ExistingEvidenceAnalysis = z.infer<typeof ExistingEvidenceAnalysisSchema>;

// =============================================================================
// Specialist Types - Evidence Relevance Scorer
// =============================================================================

/**
 * Relevance score for a specific evidence type
 */
export const EvidenceRelevanceScoreSchema = z.object({
  evidenceType: z.string(),           // "registration_card", "cancellation_policy"
  relevanceScore: z.number(),         // 0-100
  reasoning: z.string(),
  directlyDisproves: z.string().optional(),  // Which customer argument this counters
  alreadyAvailable: z.boolean().optional(),  // Whether this evidence is already on file
});

export type EvidenceRelevanceScore = z.infer<typeof EvidenceRelevanceScoreSchema>;

/**
 * Output from the Evidence Relevance Scorer specialist
 * Scores how relevant each type of evidence would be for this specific dispute
 */
export const EvidenceRelevanceScoresSchema = z.object({
  scores: z.array(EvidenceRelevanceScoreSchema),
  topPriorityEvidence: z.array(z.string()),    // Top 3-5 most critical
  lowValueEvidence: z.array(z.string()),       // Evidence not worth asking for
});

export type EvidenceRelevanceScores = z.infer<typeof EvidenceRelevanceScoresSchema>;

// =============================================================================
// Specialist Types - Evidence Plan Quality Checker
// =============================================================================

/**
 * Severity of a quality issue
 */
export const IssueSeveritySchema = z.enum(["critical", "major", "minor"]);

export type IssueSeverity = z.infer<typeof IssueSeveritySchema>;

/**
 * Category of a quality issue
 */
export const IssueCategorySchema = z.enum([
  "missing_critical_evidence",
  "claim_not_addressed",
  "wrong_priority",
  "unrealistic_requirement",
]);

export type IssueCategory = z.infer<typeof IssueCategorySchema>;

/**
 * A single quality issue found in the evidence plan
 */
export const QualityIssueSchema = z.object({
  severity: IssueSeveritySchema,
  category: IssueCategorySchema,
  description: z.string(),
  suggestedFix: z.string(),
});

export type QualityIssue = z.infer<typeof QualityIssueSchema>;

/**
 * A requirement to add during revision
 */
export const RequirementToAddSchema = z.object({
  category: z.string(),
  label: z.string(),
  description: z.string(),
  priority: z.number(),
});

export type RequirementToAdd = z.infer<typeof RequirementToAddSchema>;

/**
 * A priority change during revision
 */
export const PriorityChangeSchema = z.object({
  id: z.string(),
  newPriority: z.number(),
});

export type PriorityChange = z.infer<typeof PriorityChangeSchema>;

/**
 * Unaddressed argument identified during quality check
 */
export const UnaddressedArgumentSchema = z.object({
  argument: z.string(),
  suggestedEvidence: z.string(),
  severity: z.enum(["critical", "major", "minor"]),
});

export type UnaddressedArgument = z.infer<typeof UnaddressedArgumentSchema>;

/**
 * Instructions for revising the evidence plan
 */
export const RevisionInstructionsSchema = z.object({
  requirementsToAdd: z.array(RequirementToAddSchema),
  requirementsToRemove: z.array(z.string()),
  prioritiesToChange: z.array(PriorityChangeSchema),
  // Enriched feedback fields
  overallAssessment: z.string().optional(),
  unaddressedArguments: z.array(UnaddressedArgumentSchema).optional(),
  previousScore: z.number().optional(),
  specificGuidance: z.string().optional(),
});

export type RevisionInstructions = z.infer<typeof RevisionInstructionsSchema>;

/**
 * Output from the Evidence Plan Quality Checker specialist
 * Validates the generated evidence plan before presenting to the user
 */
export const EvidencePlanQualityCheckSchema = z.object({
  passed: z.boolean(),
  overallScore: z.number(),  // 0-100
  issues: z.array(QualityIssueSchema),
  revisionInstructions: RevisionInstructionsSchema.optional(),
});

export type EvidencePlanQualityCheck = z.infer<typeof EvidencePlanQualityCheckSchema>;

// =============================================================================
// Specialist Types - Strategy Advisor
// =============================================================================

/**
 * A defense point in the dispute strategy
 */
export const DefensePointSchema = z.object({
  point: z.string(),
  supportingEvidence: z.array(z.string()),
  addressesClaim: z.string(),
});

export type DefensePoint = z.infer<typeof DefensePointSchema>;

/**
 * Evidence priority recommendation from strategy advisor
 */
export const EvidencePrioritySchema = z.object({
  evidenceType: z.string(),
  reason: z.string(),
  alreadyAvailable: z.boolean(),
  mustGather: z.boolean(),
});

export type EvidencePriority = z.infer<typeof EvidencePrioritySchema>;

/**
 * Output from the Strategy Advisor specialist
 * Synthesizes insights from Claim Analyst, Evidence Analyzer, and Relevance Scorer
 * into a coherent dispute strategy.
 */
export const DisputeStrategySchema = z.object({
  recommendation: z.enum(["fight", "accept"]),
  confidence: z.number(), // 0-100
  primaryDefense: z.string(),
  defensePoints: z.array(DefensePointSchema),
  knownWeaknesses: z.array(z.string()),
  evidencePriority: z.array(EvidencePrioritySchema),
  approachNotes: z.string(),
});

export type DisputeStrategy = z.infer<typeof DisputeStrategySchema>;

// =============================================================================
// Specialist Context - Passed to Evidence Planner
// =============================================================================

/**
 * Context from specialists passed to the evidence planner
 */
export interface SpecialistContext {
  claimAnalysis?: ClaimAnalysis;
  relevanceScores?: EvidenceRelevanceScores;
  existingEvidence?: ExistingEvidenceAnalysis;
  codeInfo?: import("../config/disputeCodeMapping").DisputeCodeInfo;
  strategy?: DisputeStrategy;
  revisionFeedback?: RevisionInstructions;
  hasFolio?: boolean;
  respondByDate?: string;
  pmsMatch?: import("../ports").PMSMatchResult;
  merchantVertical?: "hospitality" | "ticketing" | "general";
  schemeRule?: import("../types/knowledgeBase").SchemeRule | null;
  evidenceRequirements?: import("../types/knowledgeBase").EvidenceRequirementRule | null;
  pspFormats?: import("../types/knowledgeBase").PSPFormatRule[];
  winPatterns?: import("../types/knowledgeBase").WinPattern[];
  /**
   * Pre-resolved scheme-rulebook RAG result. When the orchestrator runs a
   * revision loop, it should resolve retrieval ONCE before the loop and pass
   * the result here so subsequent attempts within the same dispute do not
   * re-issue Pinecone reads (the query is deterministic per disputeId/stage/
   * reasonCode and does not change between revisions). The planner falls
   * back to live retrieval when this is undefined, preserving the
   * back-compat single-call contract.
   */
  rulebookRagResult?: import("../services/ragPromptInjection").RulebookRagResult;
}

/**
 * Attempt context passed to the Quality Checker for revision awareness
 */
export interface AttemptContext {
  attemptNumber: number;
  previousIssues?: QualityIssue[];
  previousScore?: number;
  strategy?: DisputeStrategy;
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Initialize evidence items from a plan
 * Marks folio requirements as uploaded if folio is already available
 */
export function initializeEvidenceItems(
  plan: EvidencePlan,
  hasFolio: boolean = false,
  folioUrl?: string
): EvidenceItem[] {
  return plan.requirements.map((req) => {
    // If this is a folio requirement and folio is available, mark it as uploaded
    const isFolioRequirement =
      req.tag === "folio" ||
      (req.category === "pms_data" &&
       (req.label.toLowerCase().includes("folio") ||
        req.label.toLowerCase().includes("reservation folio")));
    
    if (isFolioRequirement && hasFolio) {
      return {
        requirementId: req.id,
        status: "uploaded" as const,
        fileName: folioUrl ? "Folio (from booking)" : "Folio",
        notes: folioUrl ? `Available from booking: ${folioUrl}` : "Available from booking",
      };
    }
    
    return {
      requirementId: req.id,
      status: "pending" as const,
    };
  });
}

/**
 * Get category display name
 */
export function getCategoryDisplayName(category: EvidenceCategory): string {
  const displayNames: Record<EvidenceCategory, string> = {
    pms_data: "Property Management Data",
    policy: "Policies & Terms",
    proof_of_stay: "Proof of Stay",
    communications: "Guest Communications",
    payment_data: "Payment Verification",
    incident_reports: "Incident Reports",
    delivery: "Delivery Proof",
    other: "Other Evidence",
  };
  return displayNames[category];
}

/**
 * Get category icon (for UI)
 */
export function getCategoryIcon(category: EvidenceCategory): string {
  const icons: Record<EvidenceCategory, string> = {
    pms_data: "building",
    policy: "document",
    proof_of_stay: "key",
    communications: "chat",
    payment_data: "credit-card",
    incident_reports: "alert",
    delivery: "truck",
    other: "folder",
  };
  return icons[category];
}
